name: antarctic_plots_binder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # runtime
  - antarctic-plots=0.1
  # interactive
  - geoviews=1.11
  - cartopy=0.22
  - ipyleaflet=0.18
  - ipython=8.18
  - ipykernel
  # viz
  - seaborn=0.13

