name: antarctic_plots_binder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # runtime
  - pygmt=0.10
  - geopandas=0.14
  - ipyleaflet=0.18
  - antarctic-plots=0.0.6
  # interactive
  - geoviews=1.11
  - cartopy=0.22
  - ipyleaflet=0.18
  - ipython=8.18
  # viz
  - seaborn=0.13
